---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    driver:
      box: curse-14.04.2
      box_url: http://cursecomms.s3-website-us-east-1.amazonaws.com/curse-14.04.2.box
      network:
        - ["forwarded_port", {guest: 80, host: 8001}]

suites:
  - name: default
    run_list:
      - recipe[apt]
      - recipe[observium]