---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.6
  - name: ubuntu-14.04
    run_list: recipe[apt]
  - name: debian-7.8
    run_list: recipe[apt]

suites:
  - name: default
    run_list: recipe[observium]
